name: wikipedia_onthisdayevents
description: On this day events from wikipedia
publish_to: 'none'
version: 1.6.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  shared_preferences: ^2.5.3
  share_plus: ^10.0.0
  url_launcher: ^6.3.1
  webfeed:
  jiffy:
  dynamic_value: ^3.0.0
  easy_dynamic_theme: ^2.3.1
  cupertino_icons: ^1.0.2
  dynamic_system_colors: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/