name: wikipedia_onthisdayevents
description: On this day events from wikipedia
publish_to: 'none'
version: 1.5.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:
  shared_preferences:
  share:
  url_launcher:
  webfeed:
  jiffy:
  dynamic_value:
  flutter_lints:
  easy_dynamic_theme:
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/